// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AcceptanceTests.Features.FunctionalTests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("PageTab Test")]
    public partial class PageTabTestFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PageTabTest.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "PageTab Test", "\tTest Each Page tabs based on User role and Program Type", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("ProviderSearch")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        [NUnit.Framework.CategoryAttribute("TableDrivenProviderSearch")]
        [NUnit.Framework.TestCaseAttribute("JPSNAdmin", "Scholarship", "EdChoice", "General,Personnel,Staff,Tuition,Docs,Status/Flags,Comments/History", null)]
        [NUnit.Framework.TestCaseAttribute("JPSNNom1", "Scholarship", "Autism", "General,Personnel,Services,Staff,Comments/History", null)]
        [NUnit.Framework.TestCaseAttribute("ProgramAdmin", "Scholarship", "Autism", "General,Personnel,Services,Staff,Docs,Status/Flags,Comments/History", null)]
        public virtual void ProviderSearch(string role, string safeLink, string program, string tabs, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "mytag",
                    "TableDrivenProviderSearch"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ProviderSearch", null, @__tags);
#line 16
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 17
 testRunner.Given(string.Format("I login as role \"{0}\"", role), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 18
 testRunner.And(string.Format("I Click on link \"{0}\"", safeLink), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
 testRunner.And(string.Format("I select the program \"{0}\"", program), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 20
 testRunner.And("I Select Provider \"Search Provider\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
 testRunner.When("I Search For Provider", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 22
 testRunner.And("I Select Provider Record 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
 testRunner.Then(string.Format("I Test All Provider Search Page \"{0}\"", tabs), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("ProviderSearch2")]
        [NUnit.Framework.CategoryAttribute("TableDrivenProviderSearch2")]
        [NUnit.Framework.TestCaseAttribute("ProgramAdmin22+", "Adult Learner", "NA", "General,Personnel,ApplicationQuestions,Participating Buildings,Docs,Status/Flags," +
            "Comments/History", null)]
        public virtual void ProviderSearch2(string role, string safeLink, string program, string tabs, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "TableDrivenProviderSearch2"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ProviderSearch2", null, @__tags);
#line 35
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 36
 testRunner.Given(string.Format("I login as role \"{0}\"", role), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 37
 testRunner.And(string.Format("I Click on link \"{0}\"", safeLink), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
 testRunner.And(string.Format("I select the program \"{0}\"", program), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 39
 testRunner.When("I Search For Provider", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 40
 testRunner.And("I Select Provider Record 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 41
 testRunner.Then(string.Format("I Test All Provider Search Page \"{0}\"", tabs), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("StudentSearch")]
        [NUnit.Framework.CategoryAttribute("TableDrivenStudentSearch")]
        [NUnit.Framework.TestCaseAttribute("JPSNAdmin", "Scholarship", "EdChoice", "Student,PARENT/GUARDIAN,INCOME VERIFICATION,Application,Assessment,Docs,Status/Fl" +
            "ags,Comments/History", null)]
        [NUnit.Framework.TestCaseAttribute("JPSNNom1", "Scholarship", "JPSN", "Student,PARENT/GUARDIAN,Application,IEP,Assessment,Docs,Status/Flags,Comments/His" +
            "tory", null)]
        [NUnit.Framework.TestCaseAttribute("JPSNAdmin", "Adult Learner", "NA", "Student,Application,Graduation Requirements,Student Success Plan,Assessment,Docs," +
            "Status/Flags,Comments/History", null)]
        public virtual void StudentSearch(string role, string safeLink, string program, string tabs, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "TableDrivenStudentSearch"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("StudentSearch", null, @__tags);
#line 50
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 51
 testRunner.Given(string.Format("I login as role \"{0}\"", role), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 52
 testRunner.And(string.Format("I Click on link \"{0}\"", safeLink), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 53
 testRunner.And(string.Format("I select the program \"{0}\"", program), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 54
 testRunner.And("I Select Student \"Search Scholarship Application\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 55
 testRunner.When("I Search For Student", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 56
 testRunner.And("I Select Student Record 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 57
 testRunner.Then(string.Format("I Test All Student Search Page \"{0}\"", tabs), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("ParentStudentSearch1")]
        [NUnit.Framework.CategoryAttribute("TableDrivenParentStudentSearch1")]
        [NUnit.Framework.TestCaseAttribute("Scholarship.Parent", "Scholarship", "Autism", "Student,PARENT/GUARDIAN,Application,IEP,Docs,Status/Flags,Comments/History", null)]
        [NUnit.Framework.TestCaseAttribute("Scholarship.Parent", "Scholarship", "JPSN", "Student,PARENT/GUARDIAN,Application,IEP,Docs,Status/Flags,Comments/History", null)]
        public virtual void ParentStudentSearch1(string parent, string safeLink, string program, string tabs, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "TableDrivenParentStudentSearch1"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ParentStudentSearch1", null, @__tags);
#line 67
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 68
 testRunner.Given(string.Format("I login as role \"{0}\"", parent), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 69
 testRunner.And(string.Format("I Click on link \"{0}\"", safeLink), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 70
 testRunner.And(string.Format("I select the program \"{0}\"", program), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 71
 testRunner.And("I Select Student \"Search Scholarship Application\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 72
 testRunner.When("I Search For Student", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 73
 testRunner.And("I Select Student Record 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 74
 testRunner.Then(string.Format("I Test All Parent Student Search Page \"{0}\"", tabs), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("ParentStudentSearch2")]
        [NUnit.Framework.CategoryAttribute("TableDrivenParentStudentSearch2")]
        [NUnit.Framework.TestCaseAttribute("Parent.CCP", "College Credit Plus", "Home School", "Student,PARENT/GUARDIAN,Application,Credit Hours,Docs,Status/Flags,Comments/Histo" +
            "ry", null)]
        [NUnit.Framework.TestCaseAttribute("Parent.CCP", "College Credit Plus", "Nonpublic", "Student,PARENT/GUARDIAN,Application,Credit Hours,Docs,Status/Flags,Comments/Histo" +
            "ry", null)]
        public virtual void ParentStudentSearch2(string parent, string safeLink, string program, string tabs, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "TableDrivenParentStudentSearch2"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ParentStudentSearch2", null, @__tags);
#line 83
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 84
 testRunner.Given(string.Format("I login as role \"{0}\"", parent), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 85
 testRunner.And(string.Format("I Click on link \"{0}\"", safeLink), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 86
 testRunner.And(string.Format("I select the parent program \"{0}\"", program), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 87
 testRunner.And("I Select Student \"Search College Credit Plus Application\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 88
 testRunner.When("I Search For Student", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 89
 testRunner.And("I Select Student Record 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 90
 testRunner.Then(string.Format("I Test All Parent Student Search Page \"{0}\"", tabs), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("FinanceSearch")]
        [NUnit.Framework.CategoryAttribute("TableDrivenFinanceSearch")]
        [NUnit.Framework.TestCaseAttribute("AutismNom1", "Scholarship", "Autism", "Allocation Form,Progress Report, Invoice,Account Summary,Payment,Finance Docs,Fin" +
            "ance Comments", null)]
        public virtual void FinanceSearch(string role, string safeLink, string program, string tabs, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "TableDrivenFinanceSearch"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("FinanceSearch", null, @__tags);
#line 99
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 100
 testRunner.Given(string.Format("I login as role \"{0}\"", role), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 101
 testRunner.And(string.Format("I Click on link \"{0}\"", safeLink), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 102
 testRunner.And(string.Format("I select the program \"{0}\"", program), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 103
 testRunner.And("I Select Finance \"Finance Search\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 104
 testRunner.When("I Search For Finance Student", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 105
 testRunner.And("I Select Finance Record 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 106
 testRunner.Then(string.Format("I Test All Student Finance Search Page \"{0}\"", tabs), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("AdminSearch")]
        [NUnit.Framework.CategoryAttribute("TableDrivenAdminSearch")]
        [NUnit.Framework.TestCaseAttribute("JPSNAdmin", "Adult Learner", "NA", "Program Management,Funding Category Setup,Billing Schedule", null)]
        [NUnit.Framework.TestCaseAttribute("JPSNAdmin", "Scholarship", "JPSN", "Program Management,Funding Category Setup,Billing Schedule,Addin/Deduct Schedule", null)]
        [NUnit.Framework.TestCaseAttribute("ProgramSpecialistAutism", "Scholarship", "Autism", "Program Management,Funding Category Setup,Billing Schedule,Addin/Deduct Schedule", null)]
        [NUnit.Framework.TestCaseAttribute("ProgramSpecialistEdChoice", "Scholarship", "EdChoice", "Program Management,Funding Category Setup,Billing Schedule,Addin/Deduct Schedule", null)]
        public virtual void AdminSearch(string role, string safeLink, string program, string tabs, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "TableDrivenAdminSearch"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("AdminSearch", null, @__tags);
#line 114
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 115
 testRunner.Given(string.Format("I login as role \"{0}\"", role), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 116
 testRunner.And(string.Format("I Click on link \"{0}\"", safeLink), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 117
 testRunner.And(string.Format("I select the program \"{0}\"", program), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 118
 testRunner.And("I Select Menu \"Admin Programs\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 119
 testRunner.And("I Select Admin Record 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 120
 testRunner.Then(string.Format("I Test All Admin Pages \"{0}\"", tabs), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
